apiVersion: v1
kind: Service
metadata:
  namespace: gateway
  name: gateway-svc
  labels:
    app: gateway
spec:
  ports:
  - port: 8080
    targetPort: 4001
    protocol: TCP
    name: mngmnt
  selector:
    app: gateway
  type: ClusterIP
