apiVersion: v1
kind: Service
metadata:
  namespace: gateway
  name: gateway-svc
  labels:
    app: gateway
spec:
  ports:
  - port: 80
    targetPort: 4000
    protocol: TCP
    name: public
  selector:
    app: gateway
  type: LoadBalancer
