apiVersion: v1
kind: Service
metadata:
  namespace: gateway
  name: db-svc
  labels:
    app: db
spec:
  ports:
  - name: postgre
    port: 5432
    targetPort: 5432
  selector:
    app: db
  type: ClusterIP
